name: topics-basics-env
channels:
- conda-forge
dependencies:
- python=3.7
- numpy
- scipy
- matplotlib
- pandas
- seaborn
- jupyter
- ipywidgets
- nbdime
- emcee
- corner
- mkl-service
- jupyter_nbextensions_configurator


